set -s escape-time 50
set -g mouse on
set -g @plugin 'tmux-plugins/tmux-sensible'
run 'tpack init'
set -g @plugin "samleeney/tmux-agent-status"
set -g extended-keys on

set -s extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'xterm\*:extkeys'
